version=0.9.11
about=Версия 0.9.11: дерево навыков, могилы, новые боссы в храме, вулкане, Древнем городе, Бездне и Небесной крепости, рыбалка, картины и фото, праздники, наёмники, доска заданий, снеговики и кошки
